export const FETCH_QUiZZES_START = 'FETCH_QUiZZES_START'
export const FETCH_QUiZZES_SUCCESS = 'FETCH_QUiZZES_SUCCESS'
export const FETCH_QUiZZES_FAIL = 'FETCH_QUiZZES_FAIL'

export const FETCH_QUiZ_SUCCESS = 'FETCH_QUiZ_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const QUIZ_RETRY = 'QUIZ_RETRY'

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'

export const ADD_QUIZ_START = 'ADD_QUIZ_START'
export const ADD_QUIZ_SUCCESS = 'ADD_QUIZ_SUCCESS'
export const ADD_QUIZ_FAIL = 'ADD_QUIZ_FAIL'

export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
